# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registrar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='registrar.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fregistrar.proto\">\n\x0breg_request\x12\x10\n\x08nVersion\x18\x01 \x01(\x05\x12\r\n\x05nTime\x18\x02 \x01(\x01\x12\x0e\n\x06\x61\x64\x64rMe\x18\x03 \x01(\t\"\x1c\n\treg_reply\x12\x0f\n\x07message\x18\x01 \x03(\t23\n\tRegistrar\x12&\n\x08register\x12\x0c.reg_request\x1a\n.reg_reply\"\x00\x62\x06proto3')
)




_REG_REQUEST = _descriptor.Descriptor(
  name='reg_request',
  full_name='reg_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nVersion', full_name='reg_request.nVersion', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nTime', full_name='reg_request.nTime', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addrMe', full_name='reg_request.addrMe', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)


_REG_REPLY = _descriptor.Descriptor(
  name='reg_reply',
  full_name='reg_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='reg_reply.message', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['reg_request'] = _REG_REQUEST
DESCRIPTOR.message_types_by_name['reg_reply'] = _REG_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

reg_request = _reflection.GeneratedProtocolMessageType('reg_request', (_message.Message,), dict(
  DESCRIPTOR = _REG_REQUEST,
  __module__ = 'registrar_pb2'
  # @@protoc_insertion_point(class_scope:reg_request)
  ))
_sym_db.RegisterMessage(reg_request)

reg_reply = _reflection.GeneratedProtocolMessageType('reg_reply', (_message.Message,), dict(
  DESCRIPTOR = _REG_REPLY,
  __module__ = 'registrar_pb2'
  # @@protoc_insertion_point(class_scope:reg_reply)
  ))
_sym_db.RegisterMessage(reg_reply)



_REGISTRAR = _descriptor.ServiceDescriptor(
  name='Registrar',
  full_name='Registrar',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=113,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='Registrar.register',
    index=0,
    containing_service=None,
    input_type=_REG_REQUEST,
    output_type=_REG_REPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRAR)

DESCRIPTOR.services_by_name['Registrar'] = _REGISTRAR

# @@protoc_insertion_point(module_scope)
