# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import registrar_pb2 as registrar__pb2


class RegistrarStub(object):
  """The registrar service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/Registrar/register',
        request_serializer=registrar__pb2.reg_request.SerializeToString,
        response_deserializer=registrar__pb2.reg_reply.FromString,
        )


class RegistrarServicer(object):
  """The registrar service definition.
  """

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RegistrarServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=registrar__pb2.reg_request.FromString,
          response_serializer=registrar__pb2.reg_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Registrar', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
