# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import full_node_pb2 as full__node__pb2


class FullNodeStub(object):
  """The handshake service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.handshake = channel.unary_unary(
        '/FullNode/handshake',
        request_serializer=full__node__pb2.hs_request.SerializeToString,
        response_deserializer=full__node__pb2.hs_reply.FromString,
        )
    self.new_transaction_broadcast = channel.unary_unary(
        '/FullNode/new_transaction_broadcast',
        request_serializer=full__node__pb2.Transaction.SerializeToString,
        response_deserializer=full__node__pb2.txn_broadcast_reply.FromString,
        )
    self.new_block_broadcast = channel.unary_unary(
        '/FullNode/new_block_broadcast',
        request_serializer=full__node__pb2.Block.SerializeToString,
        response_deserializer=full__node__pb2.block_broadcast_reply.FromString,
        )
    self.existing_block_broadcast = channel.unary_unary(
        '/FullNode/existing_block_broadcast',
        request_serializer=full__node__pb2.Block.SerializeToString,
        response_deserializer=full__node__pb2.block_broadcast_reply.FromString,
        )
    self.new_contract_broadcast = channel.unary_unary(
        '/FullNode/new_contract_broadcast',
        request_serializer=full__node__pb2.Contract.SerializeToString,
        response_deserializer=full__node__pb2.contract_broadcast_reply.FromString,
        )


class FullNodeServicer(object):
  """The handshake service definition.
  """

  def handshake(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def new_transaction_broadcast(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def new_block_broadcast(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def existing_block_broadcast(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def new_contract_broadcast(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FullNodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'handshake': grpc.unary_unary_rpc_method_handler(
          servicer.handshake,
          request_deserializer=full__node__pb2.hs_request.FromString,
          response_serializer=full__node__pb2.hs_reply.SerializeToString,
      ),
      'new_transaction_broadcast': grpc.unary_unary_rpc_method_handler(
          servicer.new_transaction_broadcast,
          request_deserializer=full__node__pb2.Transaction.FromString,
          response_serializer=full__node__pb2.txn_broadcast_reply.SerializeToString,
      ),
      'new_block_broadcast': grpc.unary_unary_rpc_method_handler(
          servicer.new_block_broadcast,
          request_deserializer=full__node__pb2.Block.FromString,
          response_serializer=full__node__pb2.block_broadcast_reply.SerializeToString,
      ),
      'existing_block_broadcast': grpc.unary_unary_rpc_method_handler(
          servicer.existing_block_broadcast,
          request_deserializer=full__node__pb2.Block.FromString,
          response_serializer=full__node__pb2.block_broadcast_reply.SerializeToString,
      ),
      'new_contract_broadcast': grpc.unary_unary_rpc_method_handler(
          servicer.new_contract_broadcast,
          request_deserializer=full__node__pb2.Contract.FromString,
          response_serializer=full__node__pb2.contract_broadcast_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FullNode', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
