# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: send_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='send_info.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsend_info.proto\"\"\n\x0f\x43ontractRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\rContractReply\x12\x11\n\tcontracts\x18\x01 \x03(\t\"&\n\x12TransactionRequest\x12\x10\n\x08txn_hash\x18\x01 \x01(\t\"#\n\x10TransactionReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x17\x43ontractCreationRequest\x12\x10\n\x08\x63ontract\x18\x01 \x01(\t\"(\n\x15\x43ontractCreationReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xca\x01\n\x08SendInfo\x12\x35\n\x0f\x43ontractDisplay\x12\x10.ContractRequest\x1a\x0e.ContractReply\"\x00\x12?\n\x13TransactionCreation\x12\x13.TransactionRequest\x1a\x11.TransactionReply\"\x00\x12\x46\n\x10\x43ontractCreation\x12\x18.ContractCreationRequest\x1a\x16.ContractCreationReply\"\x00\x62\x06proto3')
)




_CONTRACTREQUEST = _descriptor.Descriptor(
  name='ContractRequest',
  full_name='ContractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ContractRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_CONTRACTREPLY = _descriptor.Descriptor(
  name='ContractReply',
  full_name='ContractReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contracts', full_name='ContractReply.contracts', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=89,
)


_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txn_hash', full_name='TransactionRequest.txn_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=129,
)


_TRANSACTIONREPLY = _descriptor.Descriptor(
  name='TransactionReply',
  full_name='TransactionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='TransactionReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=166,
)


_CONTRACTCREATIONREQUEST = _descriptor.Descriptor(
  name='ContractCreationRequest',
  full_name='ContractCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='ContractCreationRequest.contract', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=211,
)


_CONTRACTCREATIONREPLY = _descriptor.Descriptor(
  name='ContractCreationReply',
  full_name='ContractCreationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ContractCreationReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=253,
)

DESCRIPTOR.message_types_by_name['ContractRequest'] = _CONTRACTREQUEST
DESCRIPTOR.message_types_by_name['ContractReply'] = _CONTRACTREPLY
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['TransactionReply'] = _TRANSACTIONREPLY
DESCRIPTOR.message_types_by_name['ContractCreationRequest'] = _CONTRACTCREATIONREQUEST
DESCRIPTOR.message_types_by_name['ContractCreationReply'] = _CONTRACTCREATIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractRequest = _reflection.GeneratedProtocolMessageType('ContractRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTREQUEST,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:ContractRequest)
  ))
_sym_db.RegisterMessage(ContractRequest)

ContractReply = _reflection.GeneratedProtocolMessageType('ContractReply', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTREPLY,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:ContractReply)
  ))
_sym_db.RegisterMessage(ContractReply)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONREQUEST,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:TransactionRequest)
  ))
_sym_db.RegisterMessage(TransactionRequest)

TransactionReply = _reflection.GeneratedProtocolMessageType('TransactionReply', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONREPLY,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:TransactionReply)
  ))
_sym_db.RegisterMessage(TransactionReply)

ContractCreationRequest = _reflection.GeneratedProtocolMessageType('ContractCreationRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTCREATIONREQUEST,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:ContractCreationRequest)
  ))
_sym_db.RegisterMessage(ContractCreationRequest)

ContractCreationReply = _reflection.GeneratedProtocolMessageType('ContractCreationReply', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTCREATIONREPLY,
  __module__ = 'send_info_pb2'
  # @@protoc_insertion_point(class_scope:ContractCreationReply)
  ))
_sym_db.RegisterMessage(ContractCreationReply)



_SENDINFO = _descriptor.ServiceDescriptor(
  name='SendInfo',
  full_name='SendInfo',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=256,
  serialized_end=458,
  methods=[
  _descriptor.MethodDescriptor(
    name='ContractDisplay',
    full_name='SendInfo.ContractDisplay',
    index=0,
    containing_service=None,
    input_type=_CONTRACTREQUEST,
    output_type=_CONTRACTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransactionCreation',
    full_name='SendInfo.TransactionCreation',
    index=1,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ContractCreation',
    full_name='SendInfo.ContractCreation',
    index=2,
    containing_service=None,
    input_type=_CONTRACTCREATIONREQUEST,
    output_type=_CONTRACTCREATIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINFO)

DESCRIPTOR.services_by_name['SendInfo'] = _SENDINFO

# @@protoc_insertion_point(module_scope)
